### ISSUE TITLE
Error when running under love 0.10.2

### ISSUE THREAD

**Issue by jedld** [josefnpat/doctorcatthegame#3]
When running under love 0.10.2 the following error occurs:

Error: [string "boot.lua"]:396: conf.lua:7: attempt to index field 'screen' (a nil value)

**Comment by josefnpat** [comment]
Neat! This game is ancient.

You can find the Love 0.8.0 package here: http://missingsentinelsoftware.com/content/doctor-cat-game

Let me clone and fix this up for 0.10.2

**Comment by josefnpat** [comment]
Uploaded builds at previously mentioned location!

Have fun!
